### ISSUE TITLE
Update to OpenVPN 2.5.5

### ISSUE THREAD

**Issue by kawazoe** [davisar/UbiquitiUtils#3]
Hey I just noticed your reply in the ui community and wanted to say thanks for the script!

I don't know how long you've been working on this, but about 9 months ago, I posted a comment on that thread with updated instructions to get 2.5.5 working. I've been running that version since then on my home USG-Pro. If you want, you could give it a try and consider updating your script to the newer version. Here's the link to my instructions: https://community.ui.com/questions/Connect-your-Unifi-USG-to-a-VPN-Provider-Includes-config-for-optional-extra-wireless-networks-per-c/67d49971-1841-4ccc-b0a1-71e3aaf6eb6a#answer/e136c826-fdc7-41dc-80fa-80229a8e0c3a

**Comment by davisar** [comment]
I based the script on the instructions here, posted a month or so ago:
https://community.ui.com/questions/Connect-your-Unifi-USG-to-a-VPN-Provider-Includes-config-for-optional-extra-wireless-networks-per-c/67d49971-1841-4ccc-b0a1-71e3aaf6eb6a#answer/f9f7fb01-f9a9-47af-8986-5b95c016132a

The reason for the older version is that there was a reported compatibility issue with versions of openVPN 2.5.1 and newer - perhaps your changes fix those issues?

If I can manage to find the time I may make an attempt at this (along with some other improvements), but unfortunately testing this stuff is a bear currently and takes a lot of time.

On that note if anyone knows where to get an accurate copy of the images used on the USG and USG-Pro, that would say least give a fighting chance at putting this stuff through test without firmware resets.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Etienne Maheu ***@***.***>
Sent: Wednesday, September 14, 2022 5:49:21 PM
To: davisar/UbiquitiUtils ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [davisar/UbiquitiUtils] Update to OpenVPN 2.5.5 (Issue #3)


Hey I just noticed your reply in the ui community and wanted to say thanks for the script!

I don't know how long you've been working on this, but about 9 months ago, I posted a comment on that thread with updated instructions to get 2.5.5 working. I've been running that version since then on my home USG-Pro. If you want, you could give it a try and consider updating your script to the newer version. Here's the link to my instructions: https://community.ui.com/questions/Connect-your-Unifi-USG-to-a-VPN-Provider-Includes-config-for-optional-extra-wireless-networks-per-c/67d49971-1841-4ccc-b0a1-71e3aaf6eb6a#answer/e136c826-fdc7-41dc-80fa-80229a8e0c3a<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.ui.com%2Fquestions%2FConnect-your-Unifi-USG-to-a-VPN-Provider-Includes-config-for-optional-extra-wireless-networks-per-c%2F67d49971-1841-4ccc-b0a1-71e3aaf6eb6a%23answer%2Fe136c826-fdc7-41dc-80fa-80229a8e0c3a&data=05%7C01%7C%7Ccebaf79c0b464936ce7a08da96b42117%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637987997632755841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QQIwWsLmafnRTuVKX7DQbi58V%2FKNI86n%2FRyekvVlykU%3D&reserved=0>

**Comment by kawazoe** [comment]
> perhaps your changes fix those issues?

Yes. When I noticed I needed a more recent version to support NordVPN, I just went through the entire process of getting 2.5.5 working, including validating the install with unit tests. I suspect that this person didn't read the entire comment thread and posted their own correction for 2.4.12. My solution is very different from the original and includes a custom build of libssl.

I might have made some mistakes in writing those instructions, but it's still running right now on my home setup if you need to compare with a working version. I didn't update the OS since though so there might be more stuff to figure out that showed up in newer releases.

> On that note if anyone knows where to get an accurate copy of the images used on the USG and USG-Pro, that would say least give a fighting chance at putting this stuff through test without firmware resets.

I had to reset dozens of time in that process so I definitely understand where you are coming from. The images are public. You can download them straight from unifi. However, the USG uses a MIPS architecture, not x86, so you cannot just run this stuff in a virtual machine. You would need an emulator for that specific cpu (MIPS is a family) and that's definitely not happening.

I might have some time tomorrow. I'll open a PR with a draft of my solution that you can try and play with.

**Comment by kawazoe** [comment]
@davisar I just realized what you ment by having to do a factory reset every time you try the script. I have a much easier way of testing this.

1. Go here and grab the firmware version you want to test: https://www.ui.com/download/unifi-switching-routing/unifi-security-gateway-pro-4
2. Connect to a local controller via the ip address. (Avoid cloud controllers or connecting with a url or webrtc since they require an internet connection)
3. Go into your devices tab.
4. Open the details for your USG Pro
5. In the pop-up, go to the config tab and all the way down, in manage device, use the custom firmware feature to upload the version you just downloaded.
6. Wait for the update to finish, then force provisioning.

Every time you want to revert back to the factory state, just go through step 5 and 6 again. The only thing you'll have to do is reconnect your ssh session. You don't even have to reload the page.
